default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: root
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *default
  database: qiita_clone_react_development

test:
  <<: *default
  database: qiita_clone_react_test

production:
  <<: *default
  database: qiita_clone_react_production
  username: qiita_clone_react
  password: <%= ENV['QIITA_CLONE_REACT_DATABASE_PASSWORD'] %>